/**
 * EUDPP Ontology registry
 *
 */

export const EUDPP_NS = 'https://w3id.org/eudpp#';
export const EUDPP_LCA_NS = 'http://dpp.cea.fr/EUDPP/LCA#';

const NS = EUDPP_NS;
const LCA = EUDPP_LCA_NS;

// Render categories
export type RenderCategory =
  | 'product'
  | 'dpp'
  | 'quantitative-property'
  | 'classification-code'
  | 'actor'
  | 'facility'
  | 'substance'
  | 'document'
  | 'lca'
  | 'abstract';

export const CLASS_ANCESTORS: Record<string, string[]> = {
  [`${NS}Product`]: [],
  [`${NS}DPP`]: [],
  [`${NS}ClassificationCode`]: [],

  [`${NS}Property`]: [],
  [`${NS}QuantitativeProperty`]: [`${NS}Property`],

  [`${NS}Document`]: [`${NS}Property`],
  [`${NS}DigitalInstruction`]: [`${NS}Document`, `${NS}Property`],

  [`${NS}ProductDimension`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Height`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Length`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Width`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Volume`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Weight`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}QualityIndicator`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Durability`]: [`${NS}QualityIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Reliability`]: [`${NS}QualityIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}ResourceConsumption`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EnergyConsumption`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}WaterConsumption`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}LandUse`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecycledMaterialsUse`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}SustainableRenewableMaterialsUse`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}WasteGenerationAmount`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}HazardousWasteAmount`]: [`${NS}WasteGenerationAmount`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}PackagingWasteAmount`]: [`${NS}WasteGenerationAmount`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}PlasticsWasteAmount`]: [`${NS}WasteGenerationAmount`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}CircularEconomyIndicator`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecoverableRate`]: [`${NS}CircularEconomyIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecyclingCollectionRate`]: [`${NS}CircularEconomyIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecyclingRate`]: [`${NS}CircularEconomyIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}EnvironmentalPollution`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EnvironmentalEmission`]: [`${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EmissionToAir`]: [`${NS}EnvironmentalEmission`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EmissionToSoil`]: [`${NS}EnvironmentalEmission`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EmissionToWater`]: [`${NS}EnvironmentalEmission`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}PlasticsRelease`]: [`${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}MicroplasticRelease`]: [`${NS}PlasticsRelease`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}NanoplasticRelease`]: [`${NS}PlasticsRelease`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}EnvironmentalFootprint`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}CarbonFootprint`]: [`${NS}EnvironmentalFootprint`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}MaterialFootprint`]: [`${NS}EnvironmentalFootprint`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}ProductToPackagingRatio`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}ConcentrationOfSubstanceOfConcern`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}ThresholdOfSubstanceOfConcern`]: [`${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}Actor`]: [],
  [`${NS}LegalPerson`]: [`${NS}Actor`],
  [`${NS}NaturalPerson`]: [`${NS}Actor`],
  [`${NS}Facility`]: [],

  [`${NS}Role`]: [],
  [`${NS}EconomicOperatorRole`]: [`${NS}Role`],
  [`${NS}ManufacturerRole`]: [`${NS}EconomicOperatorRole`, `${NS}Role`],
  [`${NS}AuthorisedRepresentativeRole`]: [`${NS}EconomicOperatorRole`, `${NS}Role`],
  [`${NS}ImporterRole`]: [`${NS}EconomicOperatorRole`, `${NS}Role`],
  [`${NS}DistributorRole`]: [`${NS}EconomicOperatorRole`, `${NS}Role`],
  [`${NS}DealerRole`]: [`${NS}EconomicOperatorRole`, `${NS}Role`],
  [`${NS}FulfilmentServiceProviderRole`]: [`${NS}EconomicOperatorRole`, `${NS}Role`],
  [`${NS}AuthorityRole`]: [`${NS}Role`],
  [`${NS}CustomsAuthorityRole`]: [`${NS}AuthorityRole`, `${NS}Role`],
  [`${NS}MarketSurveillanceAuthorityRole`]: [`${NS}AuthorityRole`, `${NS}Role`],
  [`${NS}ConformityAssessmentBodyRole`]: [`${NS}Role`],
  [`${NS}NotifiedBodyRole`]: [`${NS}ConformityAssessmentBodyRole`, `${NS}Role`],
  [`${NS}CredentialAgencyRole`]: [`${NS}Role`],
  [`${NS}IssuingAgencyRole`]: [`${NS}Role`],
  [`${NS}DPPServiceProviderRole`]: [`${NS}Role`],
  [`${NS}CustomerRole`]: [`${NS}Role`],
  [`${NS}ConsumerRole`]: [`${NS}CustomerRole`, `${NS}Role`],
  [`${NS}EndUserRole`]: [`${NS}Role`],
  [`${NS}IndependentOperatorRole`]: [`${NS}Role`],
  [`${NS}ProfessionalRepairerRole`]: [`${NS}Role`],
  [`${NS}RecyclerRole`]: [`${NS}Role`],
  [`${NS}RefurbisherRole`]: [`${NS}Role`],
  [`${NS}RemanufacturerRole`]: [`${NS}Role`],

  [`${NS}Substance`]: [],
  [`${NS}SubstanceOfConcern`]: [`${NS}Substance`],

  [`${LCA}Environmental_Footprint`]: [],
  [`${LCA}Carbon_Footprint`]: [`${LCA}Environmental_Footprint`],
  [`${LCA}Material_Footprint`]: [`${LCA}Environmental_Footprint`],
  [`${LCA}Impact_Category`]: [],
  [`${LCA}Impact_Category_Indicator`]: [],
  [`${LCA}Environmental_Impact`]: [],
  [`${LCA}Characterization_Factor`]: [],
  [`${LCA}Characterization_Model`]: [],
  [`${LCA}Method`]: [],
  [`${LCA}Methodology`]: [],
  [`${LCA}Impact_potential_result`]: [],
};

export const CLASS_RENDER_REGISTRY: Record<string, RenderCategory> = {
  [`${NS}Product`]: 'product',
  [`${NS}DPP`]: 'dpp',
  [`${NS}ClassificationCode`]: 'classification-code',

  [`${NS}QuantitativeProperty`]: 'quantitative-property',
  [`${NS}ProductDimension`]: 'quantitative-property',
  [`${NS}Height`]: 'quantitative-property',
  [`${NS}Length`]: 'quantitative-property',
  [`${NS}Width`]: 'quantitative-property',
  [`${NS}Volume`]: 'quantitative-property',
  [`${NS}Weight`]: 'quantitative-property',
  [`${NS}QualityIndicator`]: 'quantitative-property',
  [`${NS}Durability`]: 'quantitative-property',
  [`${NS}Reliability`]: 'quantitative-property',
  [`${NS}ResourceConsumption`]: 'quantitative-property',
  [`${NS}EnergyConsumption`]: 'quantitative-property',
  [`${NS}WaterConsumption`]: 'quantitative-property',
  [`${NS}LandUse`]: 'quantitative-property',
  [`${NS}RecycledMaterialsUse`]: 'quantitative-property',
  [`${NS}SustainableRenewableMaterialsUse`]: 'quantitative-property',
  [`${NS}WasteGenerationAmount`]: 'quantitative-property',
  [`${NS}HazardousWasteAmount`]: 'quantitative-property',
  [`${NS}PackagingWasteAmount`]: 'quantitative-property',
  [`${NS}PlasticsWasteAmount`]: 'quantitative-property',
  [`${NS}CircularEconomyIndicator`]: 'quantitative-property',
  [`${NS}RecoverableRate`]: 'quantitative-property',
  [`${NS}RecyclingCollectionRate`]: 'quantitative-property',
  [`${NS}RecyclingRate`]: 'quantitative-property',
  [`${NS}EnvironmentalPollution`]: 'quantitative-property',
  [`${NS}EnvironmentalEmission`]: 'quantitative-property',
  [`${NS}EmissionToAir`]: 'quantitative-property',
  [`${NS}EmissionToSoil`]: 'quantitative-property',
  [`${NS}EmissionToWater`]: 'quantitative-property',
  [`${NS}PlasticsRelease`]: 'quantitative-property',
  [`${NS}MicroplasticRelease`]: 'quantitative-property',
  [`${NS}NanoplasticRelease`]: 'quantitative-property',
  [`${NS}EnvironmentalFootprint`]: 'quantitative-property',
  [`${NS}CarbonFootprint`]: 'quantitative-property',
  [`${NS}MaterialFootprint`]: 'quantitative-property',
  [`${NS}ProductToPackagingRatio`]: 'quantitative-property',
  [`${NS}ConcentrationOfSubstanceOfConcern`]: 'quantitative-property',
  [`${NS}ThresholdOfSubstanceOfConcern`]: 'quantitative-property',

  [`${NS}Actor`]: 'actor',
  [`${NS}LegalPerson`]: 'actor',
  [`${NS}NaturalPerson`]: 'actor',

  [`${NS}Facility`]: 'facility',

  [`${NS}Substance`]: 'substance',
  [`${NS}SubstanceOfConcern`]: 'substance',

  [`${NS}Document`]: 'document',
  [`${NS}DigitalInstruction`]: 'document',
  [`${NS}Property`]: 'document',

  [`${LCA}Environmental_Footprint`]: 'lca',
  [`${LCA}Carbon_Footprint`]: 'lca',
  [`${LCA}Material_Footprint`]: 'lca',
  [`${LCA}Impact_Category`]: 'lca',
  [`${LCA}Impact_Category_Indicator`]: 'lca',
  [`${LCA}Environmental_Impact`]: 'lca',
  [`${LCA}Characterization_Factor`]: 'lca',
  [`${LCA}Characterization_Model`]: 'lca',
  [`${LCA}Method`]: 'lca',
  [`${LCA}Methodology`]: 'lca',
  [`${LCA}Impact_potential_result`]: 'lca',
};


export const PROPERTY_LABELS: Record<string, string> = {
  [`${NS}uniqueProductID`]: 'Unique Product ID',
  [`${NS}uniqueDPPID`]: 'Unique DPP ID',
  [`${NS}productName`]: 'Product Name',
  [`${NS}productImage`]: 'Product Image',
  [`${NS}description`]: 'Description',
  [`${NS}GTIN`]: 'GTIN',
  [`${NS}commodityCode`]: 'Commodity Code',
  [`${NS}status`]: 'DPP Status',
  [`${NS}schemaVersion`]: 'Schema Version',
  [`${NS}lastUpdate`]: 'Last Update',
  [`${NS}validFrom`]: 'Valid From',
  [`${NS}validUntil`]: 'Valid Until',
  [`${NS}linkToPreviousDPP`]: 'Link to Previous DPP',
  [`${NS}granularity`]: 'Granularity',
  [`${NS}isEnergyRelated`]: 'Energy Related',
  [`${NS}facilityID`]: 'Facility ID',
  [`${NS}codeSet`]: 'Classification Code Set',
  [`${NS}codeValue`]: 'Classification Code Value',
  [`${NS}dictionaryReference`]: 'Dictionary Reference',
  [`${NS}contentType`]: 'Content Type',
  [`${NS}value`]: 'Value',
  [`${NS}webLink`]: 'Web Link',
  [`${NS}numericalValue`]: 'Numerical Value',
  [`${NS}tolerance`]: 'Tolerance ±',
  [`${NS}actorName`]: 'Name',
  [`${NS}electronicContact`]: 'Electronic Contact',
  [`${NS}postalAddress`]: 'Postal Address',
  [`${NS}registeredTradeName`]: 'Trade Name',
  [`${NS}registeredTrademark`]: 'Trademark',
  [`${NS}uniqueOperatorID`]: 'Operator ID',
  [`${NS}uniqueFacilityID`]: 'Facility ID',
  [`${NS}nameCAS`]: 'CAS Name',
  [`${NS}nameIUPAC`]: 'IUPAC Name',
  [`${NS}numberCAS`]: 'CAS Number',
  [`${NS}numberEC`]: 'EC Number',
  [`${NS}abbreviation`]: 'Abbreviation',
  [`${NS}tradeName`]: 'Trade Name',
  [`${NS}usualName`]: 'Usual Name',
  [`${NS}otherName`]: 'Other Names',
  [`${NS}substanceLocation`]: 'Location in Product',
  [`${NS}hasImpactOnEnvironment`]: 'Impact on Environment',
  [`${NS}hasImpactOnHumanHealth`]: 'Impact on Human Health',

  [`${LCA}has_unit`]: 'Unit',
  [`${LCA}quantifies`]: 'Quantifies',
  [`${LCA}quantified_by`]: 'Quantified By',
  [`${LCA}related_to`]: 'Related To',
};

export const CLASS_LABELS: Record<string, string> = {
  [`${NS}Product`]: 'Product',
  [`${NS}DPP`]: 'Digital Product Passport',
  [`${NS}ClassificationCode`]: 'Classification Code',
  [`${NS}Actor`]: 'Actor',
  [`${NS}LegalPerson`]: 'Legal Person',
  [`${NS}NaturalPerson`]: 'Natural Person',
  [`${NS}Facility`]: 'Facility',
  [`${NS}Substance`]: 'Substance',
  [`${NS}SubstanceOfConcern`]: 'Substance of Concern',
  [`${NS}Document`]: 'Document',
  [`${NS}DigitalInstruction`]: 'Digital Instruction',
  [`${NS}QuantitativeProperty`]: 'Quantitative Property',
  [`${NS}ProductDimension`]: 'Product Dimension',
  [`${NS}EnvironmentalFootprint`]: 'Environmental Footprint',
  [`${NS}CarbonFootprint`]: 'Carbon Footprint',
  [`${NS}MaterialFootprint`]: 'Material Footprint',
  [`${NS}CircularEconomyIndicator`]: 'Circular Economy Indicator',
  [`${NS}ResourceConsumption`]: 'Resource Consumption',
  [`${NS}EnergyConsumption`]: 'Energy Consumption',
  [`${NS}WaterConsumption`]: 'Water Consumption',
  [`${NS}WasteGenerationAmount`]: 'Waste Generation',
  [`${NS}QualityIndicator`]: 'Quality Indicator',
  [`${NS}EnvironmentalPollution`]: 'Environmental Pollution',
  [`${NS}EnvironmentalEmission`]: 'Environmental Emission',
  [`${NS}Role`]: 'Role',
  [`${NS}ManufacturerRole`]: 'Manufacturer',
  [`${NS}ImporterRole`]: 'Importer',
  [`${NS}DistributorRole`]: 'Distributor',
  [`${NS}DealerRole`]: 'Dealer',
  [`${NS}AuthorisedRepresentativeRole`]: 'Authorised Representative',
  [`${NS}FulfilmentServiceProviderRole`]: 'Fulfilment Service Provider',
  [`${NS}DPPServiceProviderRole`]: 'DPP Service Provider',
  [`${NS}RecyclerRole`]: 'Recycler',
  [`${NS}RefurbisherRole`]: 'Refurbisher',
  [`${NS}RemanufacturerRole`]: 'Remanufacturer',
  [`${NS}ProfessionalRepairerRole`]: 'Professional Repairer',
  [`${NS}IndependentOperatorRole`]: 'Independent Operator',
  [`${NS}ConsumerRole`]: 'Consumer',
  [`${NS}EndUserRole`]: 'End User',
  [`${NS}IssuingAgencyRole`]: 'Issuing Agency',
  [`${NS}CredentialAgencyRole`]: 'Credential Agency',
  [`${NS}CustomsAuthorityRole`]: 'Customs Authority',
  [`${NS}MarketSurveillanceAuthorityRole`]: 'Market Surveillance Authority',
  [`${NS}NotifiedBodyRole`]: 'Notified Body',
  [`${NS}ConformityAssessmentBodyRole`]: 'Conformity Assessment Body',
  [`${LCA}Environmental_Footprint`]: 'Environmental Footprint (LCA)',
  [`${LCA}Carbon_Footprint`]: 'Carbon Footprint (LCA)',
  [`${LCA}Material_Footprint`]: 'Material Footprint (LCA)',
  [`${LCA}Impact_Category`]: 'Impact Category',
  [`${LCA}Impact_Category_Indicator`]: 'Impact Category Indicator',
  [`${LCA}Method`]: 'LCA Method',
  [`${LCA}Methodology`]: 'LCA Methodology',
};