/*
 * Copyright 2024-2027 CIRPASS-2
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * EUDPP Ontology registry
 *
 */

export const EUDPP_NS = 'https://w3id.org/eudpp#';
export const EUDPP_LCA_NS = EUDPP_NS;
export const SCHEMA_NS = 'https://schema.org/';

const NS = EUDPP_NS;
const SCHEMA = SCHEMA_NS;

// Render categories
export type RenderCategory =
  | 'product'
  | 'dpp'
  | 'quantitative-property'
  | 'classification-code'
  | 'actor'
  | 'facility'
  | 'substance'
  | 'document'
  | 'lca'
  | 'event'
  | 'abstract';

export const CLASS_ANCESTORS: Record<string, string[]> = {
  [`${NS}Product`]: [],
  [`${NS}DPP`]: [],
  [`${NS}ClassificationCode`]: [],

  [`${NS}Property`]: [],
  [`${NS}QuantitativeProperty`]: [`${NS}Property`],

  [`${NS}DocumentFormattedProperty`]: [`${NS}Property`],
  [`${NS}DigitalInstruction`]: [`${NS}DocumentFormattedProperty`, `${NS}Property`],

  [`${NS}ProductDimension`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Height`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Length`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Width`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Volume`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Weight`]: [`${NS}ProductDimension`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}QualityIndicator`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Durability`]: [`${NS}QualityIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Reliability`]: [`${NS}QualityIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}ResourceConsumption`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EnergyConsumption`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}WaterConsumption`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}LandUse`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecycledMaterialsUse`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}SustainableRenewableMaterialsUse`]: [`${NS}ResourceConsumption`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}WasteGenerationAmount`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}HazardousWasteAmount`]: [`${NS}WasteGenerationAmount`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}PackagingWasteAmount`]: [`${NS}WasteGenerationAmount`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}PlasticsWasteAmount`]: [`${NS}WasteGenerationAmount`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}CircularEconomyIndicator`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecoverableRate`]: [`${NS}CircularEconomyIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecyclingCollectionRate`]: [`${NS}CircularEconomyIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}RecyclingRate`]: [`${NS}CircularEconomyIndicator`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}EnvironmentalPollution`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EnvironmentalEmission`]: [`${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EmissionToAir`]: [`${NS}EnvironmentalEmission`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EmissionToSoil`]: [`${NS}EnvironmentalEmission`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}EmissionToWater`]: [`${NS}EnvironmentalEmission`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}PlasticsRelease`]: [`${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}MicroplasticRelease`]: [`${NS}PlasticsRelease`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}NanoplasticRelease`]: [`${NS}PlasticsRelease`, `${NS}EnvironmentalPollution`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}EnvironmentalFootprint`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}CarbonFootprint`]: [`${NS}EnvironmentalFootprint`, `${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}MaterialFootprint`]: [`${NS}EnvironmentalFootprint`, `${NS}QuantitativeProperty`, `${NS}Property`],

  [`${NS}ProductToPackagingRatio`]: [`${NS}QuantitativeProperty`, `${NS}Property`],
  [`${NS}Concentration`]: [],
  [`${NS}Threshold`]: [],

  [`${NS}Identifier`]: [],
  [`${NS}IdentifierScheme`]: [],
  [`${NS}IdentifierGranularity`]: [],
  [`${NS}ProductIdentifier`]: [`${NS}Identifier`],
  [`${NS}DPPIdentifier`]: [`${NS}Identifier`],
  [`${NS}ActorIdentifier`]: [`${NS}Identifier`],
  [`${NS}FacilityIdentifier`]: [`${NS}Identifier`],
  [`${NS}MaterialIdentifier`]: [`${NS}Identifier`],
  [`${NS}SoCIdentifier`]: [`${NS}Identifier`],
  [`${NS}ProductIdentifierScheme`]: [`${NS}IdentifierScheme`],
  [`${NS}ActorIdentifierScheme`]: [`${NS}IdentifierScheme`],
  [`${NS}MaterialIdentifierScheme`]: [`${NS}IdentifierScheme`],
  [`${NS}ProductIdentifierGranularity`]: [`${NS}IdentifierGranularity`],

  [`${NS}Actor`]: [],
  [`${NS}LegalPerson`]: [`${NS}Actor`],
  [`${NS}NaturalPerson`]: [`${NS}Actor`],
  [`${NS}Facility`]: [],

  [`${NS}ActorRoleAssignment`]: [],
  [`${NS}AuthorisedRepresentativeRoleAssignment`]: [`${NS}ActorRoleAssignment`],
  [`${NS}Role`]: [],
  [`${NS}EconomicOperatorRole`]: [`${NS}Role`],
  [`${NS}AuthorityRole`]: [`${NS}Role`],
  [`${NS}EndUserRole`]: [`${NS}Role`],
  [`${NS}CircularEconomyRole`]: [`${NS}Role`],
  [`${NS}ConformityAssessmentRole`]: [`${NS}Role`],

  [`${NS}Substance`]: [],
  [`${NS}SubstanceOfConcern`]: [`${NS}Substance`],

  [`${NS}ESPREvent`]: [],
  [`${NS}ProductEvent`]: [`${NS}ESPREvent`],
  [`${NS}DestructionEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}MaintenanceEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}MakingAvailableOnMarketEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}PlacingOnMarketEvent`]: [`${NS}MakingAvailableOnMarketEvent`, `${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}PuttingIntoServiceEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}RefurbishmentEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}RemanufacturingEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}RepairEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}UpgradingEvent`]: [`${NS}ProductEvent`, `${NS}ESPREvent`],
  [`${NS}DPPEvent`]: [`${NS}ESPREvent`],
  [`${NS}DPPArchivalEvent`]: [`${NS}DPPEvent`, `${NS}ESPREvent`],
  [`${NS}DPPCreationEvent`]: [`${NS}DPPEvent`, `${NS}ESPREvent`],
  [`${NS}DPPUpdateEvent`]: [`${NS}DPPEvent`, `${NS}ESPREvent`],
  [`${NS}EPCISCarrier`]: [],
  [`${NS}AggregationEvent`]: [`${NS}EPCISCarrier`],
  [`${NS}AssociationEvent`]: [`${NS}EPCISCarrier`],
  [`${NS}ObjectEvent`]: [`${NS}EPCISCarrier`],
  [`${NS}TransactionEvent`]: [`${NS}EPCISCarrier`],
  [`${NS}TransformationEvent`]: [`${NS}EPCISCarrier`],
  [`${NS}DPPEventRecord`]: [],

  [`${NS}LCAStudy`]: [],
  [`${NS}EPDStudy`]: [`${NS}LCAStudy`],
  [`${NS}LCAResult`]: [],
  [`${NS}LCIAResult`]: [`${NS}LCAResult`],
  [`${NS}InventoryIndicatorResult`]: [`${NS}LCAResult`],
  [`${NS}LCIAModuleValue`]: [],
  [`${NS}LCIAOrInventoryMethod`]: [],
  [`${NS}LCIAIndicator`]: [],
  [`${NS}LCIAImpactCategory`]: [],
  [`${NS}EN15804Indicator`]: [`${NS}LCIAIndicator`],
  [`${NS}EN15804ImpactIndicator`]: [`${NS}EN15804Indicator`, `${NS}LCIAIndicator`],
  [`${NS}EN15804InventoryIndicator`]: [`${NS}EN15804Indicator`, `${NS}LCIAIndicator`],
  [`${NS}LifeCycleModule`]: [],
};

export const CLASS_RENDER_REGISTRY: Record<string, RenderCategory> = {
  [`${NS}Product`]: 'product',
  [`${NS}DPP`]: 'dpp',
  [`${NS}ClassificationCode`]: 'classification-code',

  [`${NS}QuantitativeProperty`]: 'quantitative-property',
  [`${NS}ProductDimension`]: 'quantitative-property',
  [`${NS}Height`]: 'quantitative-property',
  [`${NS}Length`]: 'quantitative-property',
  [`${NS}Width`]: 'quantitative-property',
  [`${NS}Volume`]: 'quantitative-property',
  [`${NS}Weight`]: 'quantitative-property',
  [`${NS}QualityIndicator`]: 'quantitative-property',
  [`${NS}Durability`]: 'quantitative-property',
  [`${NS}Reliability`]: 'quantitative-property',
  [`${NS}ResourceConsumption`]: 'quantitative-property',
  [`${NS}EnergyConsumption`]: 'quantitative-property',
  [`${NS}WaterConsumption`]: 'quantitative-property',
  [`${NS}LandUse`]: 'quantitative-property',
  [`${NS}RecycledMaterialsUse`]: 'quantitative-property',
  [`${NS}SustainableRenewableMaterialsUse`]: 'quantitative-property',
  [`${NS}WasteGenerationAmount`]: 'quantitative-property',
  [`${NS}HazardousWasteAmount`]: 'quantitative-property',
  [`${NS}PackagingWasteAmount`]: 'quantitative-property',
  [`${NS}PlasticsWasteAmount`]: 'quantitative-property',
  [`${NS}CircularEconomyIndicator`]: 'quantitative-property',
  [`${NS}RecoverableRate`]: 'quantitative-property',
  [`${NS}RecyclingCollectionRate`]: 'quantitative-property',
  [`${NS}RecyclingRate`]: 'quantitative-property',
  [`${NS}EnvironmentalPollution`]: 'quantitative-property',
  [`${NS}EnvironmentalEmission`]: 'quantitative-property',
  [`${NS}EmissionToAir`]: 'quantitative-property',
  [`${NS}EmissionToSoil`]: 'quantitative-property',
  [`${NS}EmissionToWater`]: 'quantitative-property',
  [`${NS}PlasticsRelease`]: 'quantitative-property',
  [`${NS}MicroplasticRelease`]: 'quantitative-property',
  [`${NS}NanoplasticRelease`]: 'quantitative-property',
  [`${NS}EnvironmentalFootprint`]: 'quantitative-property',
  [`${NS}CarbonFootprint`]: 'quantitative-property',
  [`${NS}MaterialFootprint`]: 'quantitative-property',
  [`${NS}ProductToPackagingRatio`]: 'quantitative-property',

  [`${NS}Actor`]: 'actor',
  [`${NS}LegalPerson`]: 'actor',
  [`${NS}NaturalPerson`]: 'actor',

  [`${NS}Facility`]: 'facility',

  [`${NS}Substance`]: 'substance',
  [`${NS}SubstanceOfConcern`]: 'substance',

  [`${NS}ESPREvent`]: 'event',
  [`${NS}ProductEvent`]: 'event',
  [`${NS}DestructionEvent`]: 'event',
  [`${NS}MaintenanceEvent`]: 'event',
  [`${NS}MakingAvailableOnMarketEvent`]: 'event',
  [`${NS}PlacingOnMarketEvent`]: 'event',
  [`${NS}PuttingIntoServiceEvent`]: 'event',
  [`${NS}RefurbishmentEvent`]: 'event',
  [`${NS}RemanufacturingEvent`]: 'event',
  [`${NS}RepairEvent`]: 'event',
  [`${NS}UpgradingEvent`]: 'event',
  [`${NS}DPPEvent`]: 'event',
  [`${NS}DPPArchivalEvent`]: 'event',
  [`${NS}DPPCreationEvent`]: 'event',
  [`${NS}DPPUpdateEvent`]: 'event',
  [`${NS}EPCISCarrier`]: 'event',
  [`${NS}AggregationEvent`]: 'event',
  [`${NS}AssociationEvent`]: 'event',
  [`${NS}ObjectEvent`]: 'event',
  [`${NS}TransactionEvent`]: 'event',
  [`${NS}TransformationEvent`]: 'event',
  [`${NS}DPPEventRecord`]: 'event',

  [`${NS}DocumentFormattedProperty`]: 'document',
  [`${NS}DigitalInstruction`]: 'document',
  [`${NS}Property`]: 'document',

  [`${NS}LCAStudy`]: 'lca',
  [`${NS}EPDStudy`]: 'lca',
  [`${NS}LCAResult`]: 'lca',
  [`${NS}LCIAResult`]: 'lca',
  [`${NS}InventoryIndicatorResult`]: 'lca',
};


export const PROPERTY_LABELS: Record<string, string> = {
  [`${NS}hasUniqueProductIdentifier`]: 'Product Identifier',
  [`${NS}hasDigitalProductPassportId`]: 'DPP Identifier',
  [`${NS}hasUniqueOperatorIdentifier`]: 'Operator Identifier',
  [`${NS}hasUniqueFacilityIdentifier`]: 'Facility Identifier',
  [`${NS}identifierValue`]: 'Identifier Value',
  [`${NS}hasScheme`]: 'Identifier Scheme',
  [`${NS}hasGranularity`]: 'Identifier Granularity',
  [`${NS}identifierIssuedOn`]: 'Identifier Issued On',
  [`${NS}identifierExpiresOn`]: 'Identifier Expires On',
  [`${NS}identifierExampleValue`]: 'Identifier Example Value',
  [`${NS}identifierMaxLength`]: 'Identifier Maximum Length',
  [`${NS}identifierMinLength`]: 'Identifier Minimum Length',
  [`${NS}identifierPattern`]: 'Identifier Pattern',
  [`${NS}identifierSchemeIssuer`]: 'Identifier Scheme Issuer',
  [`${NS}identifierSchemeVersion`]: 'Identifier Scheme Version',
  [`${NS}productName`]: 'Product Name',
  [`${NS}productImage`]: 'Product Image',
  [`${NS}description`]: 'Description',
  [`${NS}GTIN`]: 'GTIN',
  [`${NS}commodityCode`]: 'Commodity Code',
  [`${NS}dppStatus`]: 'DPP Status',
  [`${NS}lastUpdate`]: 'Last Update',
  [`${NS}validFrom`]: 'Valid From',
  [`${NS}validUntil`]: 'Valid Until',
  [`${NS}linkToPreviousDPP`]: 'Link to Previous DPP',
  [`${NS}granularity`]: 'Granularity',
  [`${NS}isEnergyRelated`]: 'Energy Related',
  [`${NS}manufacturingDate`]: 'Manufacturing Date',
  [`${NS}codeSet`]: 'Classification Code Set',
  [`${NS}codeValue`]: 'Classification Code Value',
  [`${NS}dictionaryReference`]: 'Dictionary Reference',
  [`${NS}contentType`]: 'Content Type',
  [`${NS}value`]: 'Value',
  [`${NS}webLink`]: 'Web Link',
  [`${NS}numericalValue`]: 'Numerical Value',
  [`${NS}tolerance`]: 'Tolerance ±',
  [`${NS}actorName`]: 'Name',
  [`${NS}registeredTradeName`]: 'Trade Name',
  [`${NS}registeredTrademark`]: 'Trademark',
  [`${NS}hasActor`]: 'Actor',
  [`${NS}hasRole`]: 'Role',
  [`${NS}inContextOfProduct`]: 'Product Context',
  [`${NS}inContextOfDPP`]: 'DPP Context',
  [`${NS}assignmentValidFrom`]: 'Assignment Valid From',
  [`${NS}assignmentValidTo`]: 'Assignment Valid To',
  [`${NS}usesFacility`]: 'Uses Facility',
  [`${NS}isUsedByActor`]: 'Used By Actor',
  [`${NS}hasRepresentativeMandate`]: 'Representative Mandate',
  [`${NS}representsManufacturer`]: 'Represents Manufacturer',
  [`${SCHEMA}address`]: 'Address',
  [`${SCHEMA}email`]: 'Email',
  [`${SCHEMA}telephone`]: 'Telephone',
  [`${SCHEMA}url`]: 'Website',
  [`${SCHEMA}streetAddress`]: 'Street Address',
  [`${SCHEMA}addressLocality`]: 'City',
  [`${SCHEMA}postalCode`]: 'Postal Code',
  [`${SCHEMA}addressCountry`]: 'Country',
  [`${SCHEMA}geo`]: 'Coordinates',
  [`${SCHEMA}latitude`]: 'Latitude',
  [`${SCHEMA}longitude`]: 'Longitude',
  [`${NS}nameCAS`]: 'CAS Name',
  [`${NS}nameIUPAC`]: 'IUPAC Name',
  [`${NS}numberCAS`]: 'CAS Number',
  [`${NS}numberEC`]: 'EC Number',
  [`${NS}abbreviation`]: 'Abbreviation',
  [`${NS}tradeName`]: 'Trade Name',
  [`${NS}usualName`]: 'Usual Name',
  [`${NS}otherName`]: 'Other Names',
  [`${NS}substanceLocation`]: 'Location in Product',
  [`${NS}hasImpactOnEnvironment`]: 'Impact on Environment',
  [`${NS}hasImpactOnHumanHealth`]: 'Impact on Human Health',
  [`${NS}hasConcentration`]: 'Concentration',
  [`${NS}hasThreshold`]: 'Threshold',
  [`${NS}hasLifeCycleStage`]: 'Life Cycle Stage',
  [`${NS}eventIdentifier`]: 'Event Identifier',
  [`${NS}eventTime`]: 'Event Time',
  [`${NS}eventTimeZoneOffset`]: 'Event Time Zone Offset',
  [`${NS}recordedAt`]: 'Recorded At',
  [`${NS}dppEventRecordIdentifier`]: 'DPP Event Record Identifier',
  [`${NS}dppEventRecordedAt`]: 'DPP Event Recorded At',
  [`${NS}recordedInSystem`]: 'Recorded In System',
  [`${NS}recordedInSystemName`]: 'Recorded In System Name',
  [`${NS}hasActionType`]: 'Action Type',
  [`${NS}hasAssociationAnchor`]: 'Association Anchor',
  [`${NS}hasBusinessLocation`]: 'Business Location',
  [`${NS}hasBusinessStep`]: 'Business Step',
  [`${NS}hasBusinessTransactionContext`]: 'Business Transaction Context',
  [`${NS}hasBusinessTransactionType`]: 'Business Transaction Type',
  [`${NS}hasChildObjectContext`]: 'Child Object Context',
  [`${NS}hasChildQuantityContext`]: 'Child Quantity Context',
  [`${NS}hasDPPActionType`]: 'DPP Action Type',
  [`${NS}hasDestinationList`]: 'Destination List',
  [`${NS}hasDisposition`]: 'Disposition',
  [`${NS}hasIdentifiedObjectContext`]: 'Identified Object Context',
  [`${NS}hasInputObjectContext`]: 'Input Object Context',
  [`${NS}hasInputQuantityContext`]: 'Input Quantity Context',
  [`${NS}hasOutputObjectContext`]: 'Output Object Context',
  [`${NS}hasOutputQuantityContext`]: 'Output Quantity Context',
  [`${NS}hasParentObjectContext`]: 'Parent Object Context',
  [`${NS}hasProductEvent`]: 'Product Event',
  [`${NS}hasQuantityContext`]: 'Quantity Context',
  [`${NS}hasReadPoint`]: 'Read Point',
  [`${NS}hasSourceList`]: 'Source List',
  [`${NS}hasSourceOrDestinationEntity`]: 'Source Or Destination Entity',
  [`${NS}hasSourceOrDestinationType`]: 'Source Or Destination Type',
  [`${NS}hasTransformation`]: 'Transformation',
  [`${NS}isRecordedAs`]: 'Recorded As',
  [`${NS}isRepresentedByCarrier`]: 'Represented By Carrier',
  [`${NS}isTriggeredByProductEvent`]: 'Triggered By Product Event',
  [`${NS}recordsDPPEvent`]: 'Records DPP Event',
  [`${NS}triggersDPPEvent`]: 'Triggers DPP Event',
  [`${NS}businessTransactionIdentifier`]: 'Business Transaction Identifier',
  [`${NS}classIdentifier`]: 'Class Identifier',
  [`${NS}hasQuantityValue`]: 'Quantity Value',
  [`${NS}hasUnitOfMeasure`]: 'Unit Of Measure',
  [`${NS}instanceIdentifierValue`]: 'Instance Identifier Value',
  [`${NS}transformationIdentifier`]: 'Transformation Identifier',
  [`${NS}hasLCAResult`]: 'LCA Result',
  [`${NS}hasLCIAResult`]: 'LCIA Result',
  [`${NS}hasInventoryIndicatorResult`]: 'Inventory Indicator Result',
  [`${NS}hasModuleValue`]: 'Module Value',
  [`${NS}forLCIAOrInventoryMethod`]: 'LCIA or Inventory Method',
  [`${NS}impactCategory`]: 'Impact Category',
  [`${NS}hasUnit`]: 'Unit',
  [`${NS}amount`]: 'Amount',
  [`${NS}forModule`]: 'Life Cycle Module',
  [`${NS}forScenario`]: 'Scenario',
  [`${NS}isDeclared`]: 'Declared',
  [`${NS}accessRestrictions`]: 'Access Restrictions',
  [`${NS}areaOfProtection`]: 'Area Of Protection',
  [`${NS}baseName`]: 'Base Name',
  [`${NS}complianceStatus`]: 'Compliance Status',
  [`${NS}dataSetVersion`]: 'Data Set Version',
  [`${NS}declaresManufacturerRecord`]: 'Declares Manufacturer Record',
  [`${NS}en15804Group`]: 'EN 15804 Indicator Group',
  [`${NS}epdFormatVersion`]: 'EPD Format Version',
  [`${NS}expiryDate`]: 'Expiry Date',
  [`${NS}forIndicator`]: 'Indicator',
  [`${NS}hasComplianceDeclaration`]: 'Compliance Declaration',
  [`${NS}hasCopyright`]: 'Has Copyright',
  [`${NS}hasExternalDocumentation`]: 'External Documentation',
  [`${NS}hasImpactModel`]: 'Impact Model',
  [`${NS}hasReview`]: 'Review',
  [`${NS}ilcdFormatVersion`]: 'ILCD Format Version',
  [`${NS}impactIndicatorDescription`]: 'Impact Indicator Description',
  [`${NS}lciaOrInventoryMethodVersion`]: 'LCIA Or Inventory Method Version',
  [`${NS}licenseType`]: 'License Type',
  [`${NS}methodology`]: 'Methodology',
  [`${NS}methodologyVersion`]: 'Methodology Version',
  [`${NS}modelName`]: 'Model Name',
  [`${NS}modelVersion`]: 'Model Version',
  [`${NS}referenceToBackgroundDatabase`]: 'Background Database',
  [`${NS}referenceToCompleteReviewReport`]: 'Complete Review Report',
  [`${NS}referenceToComplianceSystem`]: 'Compliance System',
  [`${NS}referenceToDataSource`]: 'Data Source',
  [`${NS}referenceToExternalDocumentation_LCIAOrInventoryMethod`]: 'Method External Documentation',
  [`${NS}referenceToIncludedMethods`]: 'Included Methods',
  [`${NS}referenceToLCIAMethodReport`]: 'LCIA Method Report',
  [`${NS}referenceToModelSource`]: 'Model Source',
  [`${NS}referenceToOriginalEPD`]: 'Original EPD',
  [`${NS}referenceToPCR`]: 'Product Category Rules',
  [`${NS}referenceToPEFCR`]: 'Product Environmental Footprint Category Rules',
  [`${NS}referenceYear`]: 'Reference Year',
  [`${NS}registrationNumber`]: 'Registration Number',
  [`${NS}reviewDate`]: 'Review Date',
  [`${NS}typeOfReview`]: 'Type Of Review',
  [`${NS}unitAsString`]: 'Unit As String',
  [`${NS}uuid`]: 'UUID',
};

export const CLASS_LABELS: Record<string, string> = {
  [`${NS}Product`]: 'Product',
  [`${NS}DPP`]: 'Digital Product Passport',
  [`${NS}ClassificationCode`]: 'Classification Code',
  [`${NS}Actor`]: 'Actor',
  [`${NS}LegalPerson`]: 'Legal Person',
  [`${NS}NaturalPerson`]: 'Natural Person',
  [`${NS}Facility`]: 'Facility',
  [`${NS}Substance`]: 'Substance',
  [`${NS}SubstanceOfConcern`]: 'Substance of Concern',
  [`${NS}Concentration`]: 'Concentration',
  [`${NS}Threshold`]: 'Threshold',
  [`${NS}Identifier`]: 'Identifier',
  [`${NS}IdentifierScheme`]: 'Identifier Scheme',
  [`${NS}IdentifierGranularity`]: 'Identifier Granularity',
  [`${NS}ProductIdentifier`]: 'Product Identifier',
  [`${NS}DPPIdentifier`]: 'DPP Identifier',
  [`${NS}ActorIdentifier`]: 'Actor Identifier',
  [`${NS}FacilityIdentifier`]: 'Facility Identifier',
  [`${NS}MaterialIdentifier`]: 'Material Identifier',
  [`${NS}SoCIdentifier`]: 'Substance of Concern Identifier',
  [`${NS}ProductIdentifierScheme`]: 'Product Identifier Scheme',
  [`${NS}ActorIdentifierScheme`]: 'Actor Identifier Scheme',
  [`${NS}MaterialIdentifierScheme`]: 'Material Identifier Scheme',
  [`${NS}ProductIdentifierGranularity`]: 'Product Identifier Granularity',
  [`${NS}ActorRoleAssignment`]: 'Actor Role Assignment',
  [`${NS}AuthorisedRepresentativeRoleAssignment`]: 'Authorised Representative Role Assignment',
  [`${NS}ESPREvent`]: 'ESPR Event',
  [`${NS}ProductEvent`]: 'Product Event',
  [`${NS}DestructionEvent`]: 'Destruction',
  [`${NS}MaintenanceEvent`]: 'Maintenance',
  [`${NS}MakingAvailableOnMarketEvent`]: 'Making Available on the Market',
  [`${NS}PlacingOnMarketEvent`]: 'Placing on the Market',
  [`${NS}PuttingIntoServiceEvent`]: 'Putting into Service',
  [`${NS}RefurbishmentEvent`]: 'Refurbishment',
  [`${NS}RemanufacturingEvent`]: 'Remanufacturing',
  [`${NS}RepairEvent`]: 'Repair',
  [`${NS}UpgradingEvent`]: 'Upgrading',
  [`${NS}DPPEvent`]: 'DPP Event',
  [`${NS}DPPArchivalEvent`]: 'DPP Archival Event',
  [`${NS}DPPCreationEvent`]: 'DPP Creation Event',
  [`${NS}DPPUpdateEvent`]: 'DPP Update Event',
  [`${NS}DPPEventRecord`]: 'DPP Event Record',
  [`${NS}EPCISCarrier`]: 'EPCIS Carrier',
  [`${NS}AggregationEvent`]: 'Aggregation Event',
  [`${NS}AssociationEvent`]: 'Association Event',
  [`${NS}ObjectEvent`]: 'Object Event',
  [`${NS}TransactionEvent`]: 'Transaction Event',
  [`${NS}TransformationEvent`]: 'Transformation Event',
  [`${NS}ActionType`]: 'Action Type',
  [`${NS}BusinessLocation`]: 'Business Location',
  [`${NS}BusinessStep`]: 'Business Step',
  [`${NS}BusinessTransactionContext`]: 'Business Transaction Context',
  [`${NS}BusinessTransactionType`]: 'Business Transaction Type',
  [`${NS}DPPActionType`]: 'DPP Action Type',
  [`${NS}Disposition`]: 'Disposition',
  [`${NS}InstanceIdentifier`]: 'Instance Identifier',
  [`${NS}Location`]: 'Location',
  [`${NS}QuantityElement`]: 'Quantity Element',
  [`${NS}ReadPoint`]: 'Read Point',
  [`${NS}SourceOrDestination`]: 'Source Or Destination',
  [`${NS}SourceOrDestinationEntity`]: 'Source Or Destination Entity',
  [`${NS}SourceOrDestinationType`]: 'Source Or Destination Type',
  [`${NS}Transformation`]: 'Transformation',
  [`${NS}ADD`]: 'ADD',
  [`${NS}DELETE`]: 'DELETE',
  [`${NS}OBSERVE`]: 'OBSERVE',
  [`${NS}AddDPPDataAction`]: 'Add Data',
  [`${NS}CorrectDPPDataAction`]: 'Correct Data',
  [`${NS}DeleteDPPDataAction`]: 'Delete Data',
  [`${NS}ModifyDPPDataAction`]: 'Modify Data',
  [`${NS}active`]: 'Active',
  [`${NS}available`]: 'Available',
  [`${NS}commissioning`]: 'Commissioning',
  [`${NS}damaged`]: 'Damaged',
  [`${NS}destroyed`]: 'Destroyed',
  [`${NS}destroying`]: 'Destroying',
  [`${NS}disposed`]: 'Disposed',
  [`${NS}expired`]: 'Expired',
  [`${NS}in_transit`]: 'In Transit',
  [`${NS}inspecting`]: 'Inspecting',
  [`${NS}loading`]: 'Loading',
  [`${NS}other`]: 'Other',
  [`${NS}packing`]: 'Packing',
  [`${NS}recalled`]: 'Recalled',
  [`${NS}receiving`]: 'Receiving',
  [`${NS}repackaging`]: 'Repackaging',
  [`${NS}repairing`]: 'Repairing',
  [`${NS}reserved`]: 'Reserved',
  [`${NS}retail_selling`]: 'Retail Selling',
  [`${NS}returned`]: 'Returned',
  [`${NS}sellable_accessible`]: 'Sellable Accessible',
  [`${NS}sellable_not_accessible`]: 'Sellable Not Accessible',
  [`${NS}shipping`]: 'Shipping',
  [`${NS}stocking`]: 'Stocking',
  [`${NS}stolen`]: 'Stolen',
  [`${NS}storing`]: 'Storing',
  [`${NS}transporting`]: 'Transporting',
  [`${NS}unknown`]: 'Unknown',
  [`${NS}unloading`]: 'Unloading',
  [`${NS}unpacking`]: 'Unpacking',
  [`${NS}DocumentFormattedProperty`]: 'Document',
  [`${NS}DigitalInstruction`]: 'Digital Instruction',
  [`${NS}QuantitativeProperty`]: 'Quantitative Property',
  [`${NS}ProductDimension`]: 'Product Dimension',
  [`${NS}EnvironmentalFootprint`]: 'Environmental Footprint',
  [`${NS}CarbonFootprint`]: 'Carbon Footprint',
  [`${NS}MaterialFootprint`]: 'Material Footprint',
  [`${NS}CircularEconomyIndicator`]: 'Circular Economy Indicator',
  [`${NS}ResourceConsumption`]: 'Resource Consumption',
  [`${NS}EnergyConsumption`]: 'Energy Consumption',
  [`${NS}WaterConsumption`]: 'Water Consumption',
  [`${NS}WasteGenerationAmount`]: 'Waste Generation',
  [`${NS}QualityIndicator`]: 'Quality Indicator',
  [`${NS}EnvironmentalPollution`]: 'Environmental Pollution',
  [`${NS}EnvironmentalEmission`]: 'Environmental Emission',
  [`${NS}Role`]: 'Role',
  [`${NS}manufacturer`]: 'Manufacturer',
  [`${NS}importer`]: 'Importer',
  [`${NS}distributor`]: 'Distributor',
  [`${NS}dealer`]: 'Dealer',
  [`${NS}authorisedRepresentative`]: 'Authorised Representative',
  [`${NS}fulfilmentServiceProvider`]: 'Fulfilment Service Provider',
  [`${NS}dppServiceProvider`]: 'DPP Service Provider',
  [`${NS}recycler`]: 'Recycler',
  [`${NS}refurbisher`]: 'Refurbisher',
  [`${NS}remanufacturer`]: 'Remanufacturer',
  [`${NS}professionalRepairer`]: 'Professional Repairer',
  [`${NS}independentOperator`]: 'Independent Operator',
  [`${NS}consumer`]: 'Consumer',
  [`${NS}endUser`]: 'End User',
  [`${NS}issuingAgency`]: 'Issuing Agency',
  [`${NS}credentialAgency`]: 'Credential Agency',
  [`${NS}customsAuthority`]: 'Customs Authority',
  [`${NS}marketSurveillanceAuthority`]: 'Market Surveillance Authority',
  [`${NS}notifiedBody`]: 'Notified Body',
  [`${NS}conformityAssessmentBody`]: 'Conformity Assessment Body',
  [`${NS}LCAStudy`]: 'LCA Study',
  [`${NS}EPDStudy`]: 'EPD Study',
  [`${NS}LCAResult`]: 'LCA Result',
  [`${NS}LCIAResult`]: 'LCIA Result',
  [`${NS}InventoryIndicatorResult`]: 'Inventory Indicator Result',
  [`${NS}LCIAModuleValue`]: 'LCIA Module Value',
  [`${NS}LCIAOrInventoryMethod`]: 'LCIA or Inventory Method',
  [`${NS}LCIAIndicator`]: 'LCIA Indicator',
  [`${NS}LCIAImpactCategory`]: 'LCIA Impact Category',
  [`${NS}EN15804Indicator`]: 'EN 15804 Indicator',
  [`${NS}EN15804ImpactIndicator`]: 'EN 15804 Impact Indicator',
  [`${NS}EN15804InventoryIndicator`]: 'EN 15804 Inventory Indicator',
  [`${NS}LifeCycleModule`]: 'Life Cycle Module',
  [`${NS}BackgroundDatabase`]: 'Background Database',
  [`${NS}ComplianceDeclaration`]: 'Compliance Declaration',
  [`${NS}ComplianceStatus`]: 'Compliance Status',
  [`${NS}ComplianceSystem`]: 'Compliance System',
  [`${NS}EPDDocument`]: 'EPD Document',
  [`${NS}EnvironmentalFootprintScore`]: 'Environmental Footprint Score',
  [`${NS}ImpactModel`]: 'Impact Model',
  [`${NS}LCIAMethodReport`]: 'LCIA Method Report',
  [`${NS}ManufacturerRecord`]: 'Manufacturer Record',
  [`${NS}PCR`]: 'Product Category Rules',
  [`${NS}PEFCR`]: 'Product Environmental Footprint Category Rules',
  [`${NS}Review`]: 'Review',
  [`${NS}ReviewReport`]: 'Review Report',
  [`${NS}AreaOfProtection`]: 'Area Of Protection',
  [`${NS}LicenseType`]: 'License Type',
  [`${NS}EN15804IndicatorGroup`]: 'EN 15804 Indicator Group',
  [`${NS}TypeOfReview`]: 'Type Of Review',
  [`${NS}LCIAMethodology`]: 'LCIA Methodology',
  [`${NS}LCIAImpactIndicator`]: 'LCIA Impact Indicator',
  [`${NS}Source`]: 'Source',
  [`${NS}moduleA1`]: 'A1 - Raw Material Extraction And Supply',
  [`${NS}moduleA1A3`]: 'A1-A3 - Product Stage',
  [`${NS}moduleA2`]: 'A2 - Transport To Manufacturer',
  [`${NS}moduleA3`]: 'A3 - Manufacturing',
  [`${NS}moduleA4`]: 'A4 - Transport To Building Site',
  [`${NS}moduleA5`]: 'A5 - Construction Or Installation',
  [`${NS}moduleB1`]: 'B1 - Use',
  [`${NS}moduleB2`]: 'B2 - Maintenance',
  [`${NS}moduleB3`]: 'B3 - Repair',
  [`${NS}moduleB4`]: 'B4 - Replacement',
  [`${NS}moduleB5`]: 'B5 - Refurbishment',
  [`${NS}moduleB6`]: 'B6 - Operational Energy Use',
  [`${NS}moduleB7`]: 'B7 - Operational Water Use',
  [`${NS}moduleC1`]: 'C1 - Deconstruction Or Demolition',
  [`${NS}moduleC2`]: 'C2 - Transport To Waste Processing',
  [`${NS}moduleC3`]: 'C3 - Waste Processing',
  [`${NS}moduleC4`]: 'C4 - Disposal',
  [`${NS}moduleD`]: 'D - Benefits And Loads Beyond The System Boundary',
  [`${NS}fullyCompliant`]: 'Fully Compliant',
  [`${NS}partiallyCompliant`]: 'Partially Compliant',
  [`${NS}notCompliant`]: 'Not Compliant',
  [`${NS}notReviewed`]: 'Not Reviewed',
  [`${NS}accreditedThirdPartyReview`]: 'Accredited Third Party Review',
  [`${NS}dependentInternalReview`]: 'Dependent Internal Review',
  [`${NS}independentExternalReview`]: 'Independent External Review',
  [`${NS}independentInternalReview`]: 'Independent Internal Review',
  [`${NS}independentReviewPanel`]: 'Independent Review Panel',
};